### ISSUE TITLE
Excel: Notering artikel

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#100]
Ik zie in regel 6 bij reference het volgende: art. 3.1 lid 1, aanhef en onder a, Slb. Als dit de subsidieregeling lerarenbeurs ik, begrijp ik dit niet. Wat die nummering kom ik niet tegen in de regeling. Nummering in de regeling volgens wetten.nl is 1, 2, 3 enz.

**Comment by pimotte** [comment]
Volgens mij is de .1 en lid 1 dubbelop

**Comment by Rani1702** [comment]
tekstueel aangepast in excel
