### ISSUE TITLE
Excel minister vordert subsidie voor studiekosten terug

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#101]
Er zijn 2 reden om studiekosten terug te vorderen (in totaal 3) Ik zie artikel 13, tweede lid onder a dat de minister de subsidie kan terugvorderen als de leraar kort gezegd de aanvraag voor studiekosten of studieverlof intrekt. Die zie ik niet terug in de excel. In regel 10 zie ik alleen  artikel 13, eerste lid. In excel regel 17 en 18 zie ik alleen dat een leraar een aanvraag kan intrekken. Niet de bevoegdheid van de minister om in die gevallen ook te kunnen terugvorderen

**Comment by pimotte** [comment]
Denk inderdaad dat dit een missende act is, of dat `<<minister vordert kosten van collegegeld, studiemiddelen en reiskosten terug>>` aangepast moet worden

**Comment by Rani1702** [comment]
Ik heb de act terugvorderen toegevoegd (artikel 13, tweede lid, onder a Slb
