### ISSUE TITLE
Model Leraar

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#106]
Ik heb de vragen bij `<<indienen verzoek een besluit te nemen>>` beantwoord. Er verschijnt dan bij leraar een nieuwe `<<indienen verzoek een besluit te nemen>>` Dat is anders dan ik verwacht

als ik dan op de tweede `<<indienen verzoek een besluit te nemen>>` klik, krijg ik geen vragen (best prettig) maar hij verschijnt dan ook bij previous acts, zowel bij leraar als bij minister.

**Comment by pimotte** [comment]
Welke acts betreft dit?

**Comment by pimotte** [comment]
Ik ben het met je eens dat dit wat problematisch is. Het is een samenkomst van een aantal zaken:

- We onthouden de antwoorden
- We hergebruiken de antwoorden
- We staan het toe om meerdere keren een verzoek in te dienen

De basis-oplossing die ik zie is om het toe te staan om facts te verwijderen in de interface. Zo kan je modelleren dat je op een tweede vraag iets anders wil antwoorden dan op de eerste.

Iets anders wat denk ik ook relevant is, is om een manier te hebben om antwoorden te specificeren. In het geval van de vraag "is [verzoek een besluit te nemen] van toepassing?" is ja/nee eigenlijk niet genoeg. Het gaat namelijk om een specifiek verzoek, en dat geeft context voor de rest van de handelingen die daarop volgen.

**Comment by pimotte** [comment]
Verwijderen van facts: #120 
Specificeren van facts: #134 

Er staat niks anders in deze issue, dus ik sluit hem.
