### ISSUE TITLE
Model leraar: leraar vraagt subsidie voor studiekosten aan

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#107]
Als ik deze vraag beantwoord heb, dan verschuift `<<indienen verzoek een besluit te nemen>>`naar beneden en  wordt 'leraar vraagt subsidie voor studiekosten aan' geel. Dat  leraar vraagt subsidie voor studiekosten aan geel wordt is conform verwachting. Het verschuiven en zichtbaar blijven  van de tweede 'indienen verzoek een besluit te nemen'niet

**Comment by pimotte** [comment]
Het idee was om 'indienen verzoek een besluit te nemen' zo te modelleren dat het generiek is, toch? Dan voorkomt het doen van een aanvraag voor studiekosten niet dat je nog een verzoek voor iets anders indient, toch? (Sterker nog, volgens mij kan je prima nog een aanvraag voor studiekosten doen?)

Het 'verschuiven' snap ik niet helemaal, kan je dat verder uitleggen?

**Comment by Rani1702** [comment]
Ok, ik begrijp het. Dan is het wellicht nog wel raadzaam dat we in het model de aanvraag voor studiekosten en/of studieverlof opnemen. Want dat is dan de specifieke aanvraag die we in dit model willen kunnen laten doen. Enige act die ik bij leraar op dit moment zie is dat die een aanvraag intrekt.

**Comment by Rani1702** [comment]
18-7 deze situatie doet zich in het model niet meer voor
