### ISSUE TITLE
Model Aanvraagformulier studiekosten en studieverlof

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#108]
Bij onderdeel Leraar vraagt subsidie voor studiekosten krijg ik de volgende vraag als pop-up:
1.	Is ingevuld aanvraagformulier op de website van DUO van toepassing? 

Bij onderdeel Leraar vraagt subsidie voor studieverlof voor bevoegd gezag aan krijg ik de volgende vragen als pop-up
1.	Is aanvraag subsidieverlof van toepassing?
2.	Is minister van OCW van toepassing?
3.	Is ‘De aanvraag geschiedt door invulling en inlevering of elektronische verzending van daartoe bestemde door de minister te verstrekken formulieren op de website van de Dienst Uitvoering Onderwijs’ van toepassing

Waarom krijg ik bij aanvraag studieverlof meer vragen dan bij studiekosten? De wetsartikelen zijn vergelijkbaar. En vanuit het excelbestand van 11  juli haal ik dat ook niet.

**Comment by pimotte** [comment]
Als we kijken naar de excel van 11 juli, zien we:

- `<<leraar vraagt subsidie voor studiekosten aan>>`
  - Object: `[ingevuld aanvraagformulier op de website van de Dienst Uitvoering Onderwijs]`
  - Interested party: `[minister van Onderwijs, Cultuur en Wetenschap]`
  - Preconditions: Leeg

- `<<leraar vraagt subsidie voor studieverlof voor het bevoegd gezag>>`
  - Object: `[subsidie voor studieverlof]`
  - Interested party: `[minister van OCW]`
  - Preconditions: `[aanvraag geschiedt door invulling en inlevering of elektronische verzending van daartoe bestemde door de minister te verstrekken formulieren]`

Dit correspondeert precies met de vragen die je krijgt. In het geval van `[minister van OCW]`, als we dit wijzigen naar `[minister van Onderwijs, Cultuur en Wetenschap]`, vervalt deze vraag, omdat wij in de demo aangeven dat `[minister van Onderwijs, Cultuur en Wetenschap]` een identiteit heeft, en daarom bestaat.

Ik denk dat we dit inderdaag gelijk willen trekken, en dan zou het denk ik logisch zijn om de subsidie voor studieverlof te wijzigen naar hoe studiekosten is ingericht.

**Comment by Rani1702** [comment]
Eens met je eindconclusie

**Comment by Rani1702** [comment]
In het tabblad facts heb ik bij aanvraagformulieren op website DUO (regel 16) de volgende opmerking gemaakt: Pim en ik gaan aanvraagformulieren voor studiekosten en studieverlof als 1 modelleren. Vandaar in deze regel ook 1 'aanvraagformulieren Nog even bewust niets gedaan met source tekst enz.. 

Wellicht nog aanpassen na onze werksessie op 24 juli

**Comment by Rani1702** [comment]
Vgl issue 96
