### ISSUE TITLE
Excel: aanvragen studiekosten en /of studieverlof

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#109]
Moeten we niet expliciet aangeven in het excelbestand dat een leraar 2 (misschien 3) dingen kan aanvragen?

1. studiekosten
2. studiekosten en studieverlof
3. studieverlof

Ik zie dat in de acts nog niet terug

**Comment by pimotte** [comment]
Modelmatig lijkt het me logisch om alleen 1 en 3 te doen. Als een leraar namelijk beide wil doen, zal deze ook beide acts uitvoeren. 

Alleen als het wets-technisch een atomaire actie moet zijn, zou ik ook optie 2 modelleren, maar in de Slb zijn het juist losse artikelen

**Comment by Rani1702** [comment]
Eens
