### ISSUE TITLE
Model ministerkant: na acts hardheidsclausule, bepalen hoogte subsidie

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#111]
Na acts handheidsclausule en bepalen hoogte subsidie verwacht ik act: nemen besluit/ maken beschikking/ bekendmaken besluit of zoiets. Na de beoordeling van het verzoek, neemt de minister een besluit en dat besluit moet kenbaar gemaakt worden aan de belanghebbende (in dit geval de leraar)

**Comment by pimotte** [comment]
Bekendmaken besluit wordt zichtbaar in het geval dat een act een `[besluit]` create. Je kan deze dus toevoegen op plekken waarvan het logisch is dat het besluit bekend moet worden gemaakt.

**Comment by Rani1702** [comment]
Deze begrijp ik niet helemaal

**Comment by Rani1702** [comment]
Als ik na hardheidsclausule en /of bepalen hoogte subsidie een besluit wil bekendmaken. 'regel'ik dat in de kolom create. als in deze kolom al dingen staan, dan is ' ; ' het scheidingsteken

**Comment by Rani1702** [comment]
Na hardheidsclausule in kolom create `<bekend maken van een besluit>` gezet. Niet in bepalen hoogte subsidie, want strikt genomen, moet je dan nog besluit nemen, voordat je kan bekend maken. Wel heb ik bij acts zoals als weigeren subsidie `<bekend maken van een besluit>` toegevoegd
