### ISSUE TITLE
Model ministerkant: stelt bedrag voor doelgroep beschikbaar

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#112]
Na beantwoording van de vraag Is 'beschikbaar bedrag van toepassing'? krijg ik de vraag 'Is wetgevende macht van toepassing'? Die vraag begrijp ik niet in deze context. Denk puntje Robert?

**Comment by pimotte** [comment]
Volgens het model is de `interested party` de wetgevende macht. Hierdoor wordt gevraagd of deze bestaat. Ik weet niet of dat inderdaad de interested party zou moeten zijn.

**Comment by Rani1702** [comment]
Nog wel even overleg met Robert of hij dan de hele wetgevende macht bedoeld. Dan krijg je namelijk wel wat over je heen.

**Comment by Rani1702** [comment]
De minister in artikel 6, eerste lid Slb is ten aanzien van de uitvoering hiervan verantwoording schuldig aan de wetgevende macht. De wetgevende macht is hier regering. Dit aanpassen in de excel. Regering is interesed party.

**Comment by Rani1702** [comment]
Aangepast in excel, werkblad acts
