### ISSUE TITLE
Feature request: Terugdraai mogelijkheid

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#113]
Is het mogelijk de interface zo bouwen dat ik terug kan in het model? Nu moet ik steeds F5-en en het bestand opnieuw uploaden.

**Comment by pimotte** [comment]
Jazeker.

Makkelijk: Zorgen dat je een knop hebt waar mee je naar de begin-staat kan, zorgen dat je facts kan verwijderen
Moeilijker: 1 act terugstappen
