### ISSUE TITLE
Verwijzing zoeken bij [aanvrager]

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#124]
19-7 Bij kolom interested party aanvrager gewijzigd in belanghebbende, omdat belanghebbende de wettelijke term is. De term aanvrager wordt in de Awb niet gedefinieerd en belanghebbende wel. De belanghebbende doet een aanvraag. In de excel bij regel 26 van acts. Voordat ik de facts  aanpas (en dus ook de de acts op de verschillende plaatsten) graag even overleg of dat ook is wat we willen

**Comment by pimotte** [comment]
aanvrager komt van mij, als dat wettelijk nonsens is lijkt het me logisch dit te wijzigen

**Comment by pimotte** [comment]
Aanvrager wordt waarschijnlijk ergens gedefinieerd, heeft een verwijzing nodig

**Comment by Rani1702** [comment]
Aanvrager wordt als term wel gebruikt in de Awb. In de Awb is er geen definitie gegeven. Ik heb hier dus ook geen verwijzing voor. Ik heb wel een reden gevonden waarom de Awb het in een aantal artikelen wel over aanvrager heeft. Dat is omdat een aanvrager niet altijd de belanghebbende is. Zie T&C Awb, commentaar op art. 3:13 Awb, J. Verbeek. Ik sluit het issue
