### ISSUE TITLE
De fact nadelige gevolgen van een besluit zijn onevenredig in verhouding tot de met het besluit te dienen doelen

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#125]
Hetgeen nu in de fact staat, is een situatie die volgens art. 3:4 lid 2 niet voor mag komen. Waarom is dit dan nu wel een fact? Regel 22 van de excel

**Comment by pimotte** [comment]
Ik kan me voorstellen dat het ergens in de precondition van een besluit thuis hoort. Op dit moment wordt deze fact nergens gebruikt

**Comment by Rani1702** [comment]
Uitwerken bij hardheidsclausule.Technisch het komt in een precondition van een act die leidt tot een besluit

**Comment by Rani1702** [comment]
Uitgewerkt bij hardheidsclausule
