### ISSUE TITLE
Beantwoording vraag bij fact formulier voor het indienen van aanvragen en het verstrekken van gegevens is vastgesteld door bestuursorgaan

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#126]
(1) Is er een betere verwijzing te vinden als bron voor het indienen van een aanvraag? 
(2) Is het indienen nodig als concept? Het beschrijft eigenlijk een handeling.
(3) Artikel 4:4 Awb is gewijzigd voor het in werking is getreden. Daarom is de versie die vanaf 01-01-1994 van kracht is de tweede versie van dit artikel. (excel regel 20)

Antwoord op vraag 1: 
Hier zou je artikel 4:1 Awb voor kunnen gebruiken.

Antwoord op vraag 2:
Ik denk dat we hier een act beschrijven, geen fact

**Comment by pimotte** [comment]
Vraag 2: Ik denk dat de fact `[formulier voor het indienen van aanvragen en het verstrekken van gegevens]` ge-create zou worden door de act `<<verstrekken formulier voor het indienen van aanvragen en verstrekken van gegevens>>`

**Comment by Rani1702** [comment]
Was een interne vraag van Robert
