### ISSUE TITLE
Volgorde voorwaarden niet in behandeling nemen

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#127]
Regel 23 t/ 26 van facts. Is er een reden om in de excel af te wijken van de volgorde van de wetstekst?

**Comment by pimotte** [comment]
In principe maakt dit niks uit (je mag ze van mij omdraaien.

Wat me het belangrijkste lijkt om duidelijk de link naar de wet te leggen is dat ze in de pre-condition (Acts, F4) in dezelfde volgorde staan als in de wet, en dat is in dit geval in orde.

**Comment by Rani1702** [comment]
Volgorde wet volgen. Pim heeft dit opgelost
