### ISSUE TITLE
Besluit om de aanvraag niet te behandelen wordt aan de aanvrager

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#128]
besluit om de aanvraag niet te behandelen wordt aan de aanvrager bekendgemaakt binnen vier weken nadat de aanvraag is aangevuld of nadat de daarvoor gestelde termijn ongebruikt is verstreken

Door het woord 'wordt' ben ik in de veronderstelling dat dit een handeling (act) is en niet een fact. Graag overleg, ook al omdat de function ook een fact bevat.

**Comment by pimotte** [comment]
Er zijn hier volgens mij 2 dingen gaande:

- Het besluit tot niet te behandelen moet binnen vier weken na aanvulling, of nadat de gestelde termijn ongebruikt is verstreken
- Dit besluit moet bekend worden gemaakt

Ik vermoed dat de logsiche manier is om dit te modeleren:

- Duty voor het bekendmaken (met de conditie voor de timing)
- Pre-condition voor het nemen van het besluit (mbt tot de timing)

**Comment by Rani1702** [comment]
nemen besluit en bekend maken besluit zijn losse functies. Oplossing Pim doorvoeren. Nw variant bekend maken bessuit toevoegen. (4-wekentermijn)

**Comment by Rani1702** [comment]
Oplossing Pim doorgevoerd
