### ISSUE TITLE
Aanvulling op fact bestuursorgaan is bevoegd  op de aanvraag te beslissen

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#129]
Is artikel 1:3, eerste lid Awb niet hier ook relevant? Onder besluit wordt verstaan: een schriftelijke beslissing van een bestuursorgaan, inhoudende een publiekrechtelijke rechtshandeling.

**Comment by pimotte** [comment]
Het is nu zo dat het fact besluit alleen voort kan komen uit acts. Ik vermoed dat we het niet tot dit niveau uit willen modeleren omdat het dan wat detailistisch wordt.
