### ISSUE TITLE
Excelbestand dubbel fact?

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#131]
Regel 38 en regel 44 lijken precies hetzelfde. subsidie kan verleend worden voor één studiejaar en één opleiding  Als dat zo is, is daar een reden voor?

**Comment by pimotte** [comment]
Is denk ik een foutje wat is ontstaan door de encoding. Kan inderdaad ontdubbeld worden.

**Comment by Rani1702** [comment]
ga ik na bespreking met Robert aanpassen, anders kloppen al mijn verwijzingen niet meer

**Comment by Rani1702** [comment]
De eerste keer dat de regel voorkomt heb ik laten staan. De tweede verwijderd.
