### ISSUE TITLE
Meerdere juriconnect urls in 1 veld

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#132]
Regel 42. Deze regel verwijst naar 2 artikelen. Hoe doe ik dat met de verwijzingen naar juriconnect? Ik begreep dat het wenselijk is één juriconnectverwijzing in 1 cel te hebben

**Comment by pimotte** [comment]
Denk het wel. Het is logisch om dit nog even met Robert te bespreken. Het zou zo kunnen zijn dat meerdere juriconnect verwijzingen in 1 veld een indicatie is dat er iets slecht is gemodelleerd, dus in dat geval zouden we het expliciet niet willen ondersteunen.

**Comment by pimotte** [comment]
Zowel versie als juriconnect kunnen dubbel

**Comment by pimotte** [comment]
Fixed (sources array)
