### ISSUE TITLE
Facts besluit tot verlenen subsidie voor studiekosten van een leraar in verband met het volgen van een opleiding

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#140]
Ik zie wel dat de Minister van alles doet/mag doen, beslissen binnen een termijn, hoogte subsidie bepalen enz. Weet bij dit specifieke fact niet zo snel ene wetsverwijzing.
Excel regel 62, van Fact

**Comment by pimotte** [comment]
Dit is er weer zo eentje die ik heb toegevoegd om bepaalde volgordelijkheid af te dwingen. In dit geval is het een precondition voor oa terugvordering.

Het zou kunnen dat dit iets generieker moet en dat het uit de kaderregeling of uit de awb zou moeten komen.

**Comment by Rani1702** [comment]
Artikel 4:23, eerste lid Awb als verwijzing toegevoegd. Is de algemene bevoegdheid van een bestuursorgaan om subsidie te verlenen als daarvoor een wettelijke basis voor is
