### ISSUE TITLE
Kan verzoek niet intrekken

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#143]
Ik heb alle vragen (indienen verzoek, subsidie studiekosten, subsidie studieverlof) positief beantwoord. Ik verwacht dan nog "leraar trekt verzoek in". Want deze handeling kan een leraar dan nog doen en die kan die doen als alle voorgaande  positief zijn.

**Comment by pimotte** [comment]
Mee eens. Deze acts bestaan ook : `<<leraar trekt aanvraag subsidie voor studiekosten in>>` en `<<leraar trekt aanvraag subsidie voor studieverlof in>>`.

Als het goed zijn `<<leraar vraagt subsidie voor studiekosten aan>>` en `<<leraar vraagt subsidie voor studieverlof voor het bevoegd gezag>>` de acts die dit mogelijk maken

**Comment by Rani1702** [comment]
Ik zal bij de acts `<<leraar vraagt subsidie voor studiekosten aan>>` en `<<leraar vraagt subsidie voor studieverlof voor het bevoegd gezag aan>>` in de kolom create ook het intrekken toevoegen

**Comment by Rani1702** [comment]
Na overleg nog een openstaande vraag: Wanneer moet je de act intrekken te zien krijgen? Zie gesprek in slack van 24 -7 rond 10:00 u

**Comment by pimotte** [comment]
Opgelost samen met #108
