### ISSUE TITLE
Formulering ingevuld aanvraagformulier

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#144]
Is [ingevuld aanvraagformulier op de website van de Dienst Uitvoering Onderwijs] van toepassing?

Ik heb moeite met de formulering van deze vraag. Zou meer moeten zijn in de trant: Is het aanvraagformulier ingevuld dat op de website van DUO staat?
Zoals het er nu staat, lijk je het formulier alleen maar elektronisch te kunnen verzenden.

**Comment by pimotte** [comment]
Laten we dit meenemen wanneer we de acts van formulieren verzenden en doen van de aanvraag samenvoegen (#108)

**Comment by pimotte** [comment]
Bewust alleen electronisch gemodelleerd (fysieke aanvraag zou gaan via `<<indienen verzoek een besluit te nemen>>`)
