### ISSUE TITLE
Reintroduce short-circuit of different flint items when one is false

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#145]
Heb vraag Is [subsidie voor studieverlof] van toepassing? met annuleren beantwoord. Ik krijg dan ook de andere vragen nog. Ik verwacht dan dat de actie"not allowed "is. Omdat je meteen aan de eerste vraag al niet voldoet. 

Ook als ik " minister OCW van toepassing"annuleer verwacht ik een "not allowed"

**Comment by pimotte** [comment]
Ah. Ja. Hier komen twee dingen samen die een beetje ongelukkig zijn.

Op het moment dat we bepalen of iets wel of niet mogelijk is, moeten we alles afgaan. Op het moment dat we de vragen stellen willen we denk ik inderdaad meteen stoppen.
