### ISSUE TITLE
Act minister betaalt subsidiebedrag

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#147]
Als de acts leraar vraag subsidie studiekosten en leraar vraag subsidie studieverlof, dan verwacht ik ook de act "subsidiebedrag wordt uitbetaald" Die zie ik in de interface nog niet terug. Wel de act `<<minister weigert subsidieverlening aan een leraar>>`

**Comment by pimotte** [comment]
In de acts waarin de subsidie verstrekt wordt, wordt de uitbetaling als een duty gecreeerd. Deze staat echter niet in de lijst van duties, waarschijnlijk wordt deze daardoor niet als duty weergegeven.

Ik vermoed dat de oplossing is: Deze duty uitmodelleren

**Comment by Rani1702** [comment]
Heb duty `<minister van OCW betaalt subsidie studiekosten aan leraar>` aangemaakt.
