### ISSUE TITLE
Change alert to in-page pop-over

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#149]
Als ik op  'act' klik van de act `<<leraar vraagt subsidie voor studiekosten aan>>` krijg ik geen vraag, maar verdwijnt act deze meteen. Ik zie dan in wallet of false of previous acts niets terug. (alleen de zaken van indienen verzoek besluit te nemen)

Zelfde gebeurt bij de act  aanvragen studieverlof

**Comment by pimotte** [comment]
Vermoedelijk komt dit doordat aangegeven is dat firefox de pop-ups moet blokkeren.

In het algemeen geeft de ingebouwde popup nogal wat problemen, dus het is waarschijnlijk wel de moeite waard om deze in de pagina zelf te trekken.

**Comment by Rani1702** [comment]
Eens. Dan issue laten staan en een functional van maken?
