### ISSUE TITLE
Toelichting preconditie verzoek

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#82]
Bij preconditie verzoek zie ik de tekst: "NIET [bij wettelijk voorschrift is anders bepaald]" Op welke juridische bron is deze gebaseerd. Ik vind hem niet in de Regeling zelf, de bovenliggende wet of de Awb ? Excel 190709 Acts Rani bewerking2

**Comment by pimotte** [comment]
Het betreft https://wetten.overheid.nl/jci1.3:c:BWBR0005537&hoofdstuk=4&titeldeel=4.1&afdeling=4.1.1&artikel=4:1&z=2019-07-01&g=2019-07-01

**Comment by pimotte** [comment]
Merk op: Omdat het in het geval van de lerarenbeurs het wel bij wettelijk voorschrift anders is bepaald, voeren we deze act nooit daadwerkelijk uit. Deze frame kan wel relevant zijn op het moment dat we dit breder willen toepassen.
