### ISSUE TITLE
Model niet behandelen minister

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#83]
de act 'besluiten de aanvraag niet te behandelen' hier heb ik de a, b, en c voorwaarden (a, b, c van artikel 4:5 Awb) als niet waar gekwalificeerd. Dan moet je de aanvraag behandelen. Ik zie niet terug dat dat dan ook gebeurt. Als het zo is dat alleen de ware vragen geel worden, dan lijkt dit goed te gaan. Graag bevestiging.

**Comment by pimotte** [comment]
@Rani1702 Volgens mij hadden we geconstateerd dat deze goed ging als we het vanaf het begin opnieuw probeerden?
