### ISSUE TITLE
Model Minister buiten toepassing regeling of afwijken van regeling

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#84]
Minister kan een of meer bepalingen subsidieregeling buiten toepassing laten of afwijken van de subsidieregeling. Ik zie hier in de subsidieregeling zelf geen grond voor. Als je conform artikel 3, vierde lid, afwijkt van het derde lid, hou je je nog wel aan de regeling zelf, Toch?

**Comment by pimotte** [comment]
Dit gaat over de hardheidsclausule, toch? https://wetten.overheid.nl/BWBR0039319/2019-04-01/#Hoofdstuk4_Artikel26
