### ISSUE TITLE
Aanvraag schriftelijk, tenzij bij wettelijk voorschrift (art 4:1 Awb)

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#87]
In een toelichting bij het model aangeven dat ook aan tenzij bij wettelijk voorschrift anders bepaald in het geval bij de subsidieregeling is voldaan. Omdat in de regeling is aangegeven dat je de aanvraag ook via elektronische weg kan doen. artikel 7 en 8 Subsidieregeling lerarenbeurs

**Comment by pimotte** [comment]
Gerelateerd aan #94 Het schriftelijk doen van de aanvraag is generiek
