### ISSUE TITLE
Indienen verzoek en bekend maken besluit

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#93]
In de excel gegenereerd vanuit het model, werkblad 'acts' zie ik bij indienen verzoek bij create een aantal zaken terug die ik ook verder terug verwacht in acts en niet alleen bij duties. Zelfde geldt voor bekend maken besluit bij terminate.

**Comment by pimotte** [comment]
Er is een plan om de huidige duties te laten zien, maar niet het uitvoeren ervan vast te leggen. Ik denk dat dat in ieder geval dit een stap ernaartoe is.

**Comment by Rani1702** [comment]
Wil ik het morgen met jou en Robert dan nog even over hebben

**Comment by pimotte** [comment]
#105 aangemaakt om duty-interface vast te leggen. De duties worden verder uitgewerkt in #92
