### ISSUE TITLE
Besluiten aanvraag niet te behandelen

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#94]
Vanuit de excel bij het werkblad 'acts' en dan besluiten de aanvraag niet te behandelen (rij 4) cel preconditions: Geldt de NIET aan het begin van de cel voor de hele rest van de cel? Als NIET voor de hele cel geldt, dan graag samen checken of de uitkomst van de eerste bepaling (4:5, eerste lid onder a Awb) goed gaat

**Comment by pimotte** [comment]
Er staan haakjes om de NIET: (
NIET [aanvrager heeft voldaan aan enig wettelijk voorschrift voor het in behandeling nemen van de aanvraag])

Dit betekent dat de NIET alleen van toepassing is op de fact die volgt. Volgens mij gedraagt zich dit correct.

**Comment by Rani1702** [comment]
Gaat goed

**Comment by Rani1702** [comment]
gaat goed
