### ISSUE TITLE
Feature request: Kleur in model?

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#95]
Als ik de vraag doorlopen heb, zou het fijn zijn als dat ook in het model zichtbaar is, bijv. met een kleur. Volgens mij ben je dit al aan het wijzigen. Maak het toch als issue, zodat het op je takenlijst blijft, als een friendly reminder

**Comment by pimotte** [comment]
Wat bedoel je met "de vraag doorlopen heb"? De vragen zelf zijn niet zichtbaar in het hoofdscherm, daar hebben we acts, wallet en previous acts staan (Maar previous acts is niet wat je zoekt?)

**Comment by Rani1702** [comment]
Als ik bijvoorbeeld bij vaststellen formulier verstrekken gegevens op act klik, dan krijg ik via een pop-up een aantal vragen die ik met ja of annuleer beantwoord. Als ik die pop ups heb doorlopen, dan ben ik klaar met vaststellen forumilier verstrekken. Bij leraar krijg ie wel een kleur geel mee, trouwens ook niet in alle gevallen

**Comment by Rani1702** [comment]
Startvraag altijd noteren en via wallet en previous acts gebruikerswensen formuleren
