### ISSUE TITLE
Model minister vaststellen formulier verstrekken gegevens

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#96]
Ik zie in het model als ik de vragen bij vaststellen formulier verstekken gegeven heb beantwoord ik in previous acts 'indienen verzoek besluit te nemen'. Qua model klopt dat, want ik had die vraag (indienen verzoek) beantwoord, maar

Dit lijkt me principieel fout, omdat een leraar verplicht is gebruik te maken van het formulier. Dus het indienen van een verzoek kan niet voorafgaan aan het vaststellen formulier.  
Dus eigenlijk moet ik de vraag over het indienen van een verzoek (aan de lerarenkant) pas te zien krijgen als ik vaststellen formulier bij ministerkant positief heb beantwoord. 

Na opnieuw laden ben ik begonnen bij vaststellen formulier en kreeg ik die melding niet en dat is ook zoals ik het verwacht

**Comment by pimotte** [comment]
Samenvattend zeg je:

- 'indienen verzoek besluit te nemen' zou pas zichtbaar moeten zijn na verstrekken van formulieren

Correct?
Ik denk dat we hier rekening moeten houden met dat 'indienen verzoek besluit te nemen' een generieke actie is uit de AWB, en dus sowieso kan, ongeacht de lerarenbeurs-context, of is dat niet logsich?

**Comment by Rani1702** [comment]
Dat zou ik niet logisch vinden, omdat we nu juist bezig zijn met de lerarenbeurs. We modelleren hier de Awb in de context van de lerarenbeurs.. Gaan we het met Robert over hebben

**Comment by Rani1702** [comment]
Vaststellen formulier maakt een fact aan dat een precondition moet zijn voor verzenden aanvraagformulier.
de factframe die dan gemaakt wordt, heeft als function `<<>>`

**Comment by Rani1702** [comment]
Oplossing: mergen naar 1 act van verzenden formulier en aanvraag subsidie/studieverlof

**Comment by Rani1702** [comment]
Vgl. issue 108
