### ISSUE TITLE
Model: indienen verzoek besluit te nemen

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#97]
Als ik de vraag 'tenzij bij wettelijk voorschrift anders bepaald' positief beantwoord, krijg ik niet de vraag aan de ministerkant over het buiten behandeling stellen. Dat verwacht ik wel. 

Artikel 4:1 Awb "tenzij anders bij wettelijk voorschrift anders bepaald ziet ook op het schriftelijk indienen van een aanvraag/verzoek'
Graag met Robert en Pim bespreken.

**Comment by pimotte** [comment]
Volgens mij is dit hetzelfde als #82 

Kunnen we een van deze twee issues sluiten?

**Comment by Rani1702** [comment]
Nee, liever niet sluiten maar allebei even bespreken met Robert. Sorry, ben nog even aan de voorzichtige kant en in dit stadium van inwerken, stel ik liever een vraag  te veel dan te weinig.
