### ISSUE TITLE
Excel minister verstrekt subsidie lerarenbeurs aan leraar

### ISSUE THREAD

**Issue by Rani1702** [discipl/ComplianceByDesign#99]
Regel 6 Vraag bij explanation
Bevat het besluit ook de hoogte van het subsidiebedrag? In de beschikking staat dit bedrag wel, de vraag is of we het modelleren als een aparte handeling. 
Rani: Ja, zie artikel 4:31 Awb

na overleg met Robert: zijn 2 besluiten, wordt bekendgemaakt in 1 document. Vgl. meeromvattende beschikking Vw 2000

## Weigeringsgronden

Er zijn geen aparte gronden voor afwijzing en buiten behandeling stellen. Impliceert dat, dat wordt afgewezen als niet wordt voldaan aan een voorwaarde voor verstrekken, en alleen buiten behandeling wordt gesteld op grond van art. 4:5 Awb?

Rani: Lijkt mij dat er in artikel 10 van de subsidieregeling een afwijzingsgrond staat. Verder staan in artikel 4:35 Awb afwijzingsgronden voor subsidie. 
Buiten behandelingstelling kan alleen op grond van artikel 4:5 Awb. NB artikel 6, tweede lid, van de subsidieregeling geeft wel invulling aan de zinsnede 'mits de aanvrager de gelegenheid heeft gehad de aanvraag binnen een door het bestuursorgaan gestelde termijn aan te vullen.' van artikel 4:5, eerste lid, van de Awb. 

Na overleg met Robert: toevoegen in model art 10 Slb en art 4:35 Awb

**Comment by pimotte** [comment]
"toevoegen in model art 10 Slb en art 4:35 Awb" kan gebeuren, de bovenste heb ik niet meer helder wat we hier concreet gaan doen, maar wellicht kan dat ook gemodelleerd worden?

**Comment by Rani1702** [comment]
Weigeringsgrond art 4:35 Awb toegevoegd
